apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  labels:
    app: products
    kubernetes.azure.com/generator: devhub
  namespace: tinyshopproducts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: arteiroacr.azurecr.io/products:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
