apiVersion: v1
kind: Service
metadata:
  name: products
  namespace: tinyshop
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: ClientIP
  selector:
    app: products
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
